# Snakefile that does the following:
# runs python3 ./app.py 10 times

        
results = "output_{i}.txt"

all_results = expand(results, i = [x for x in range(10)] )

rule all:
    input:
        all_results
    run:
        print(all_results)

rule run_app:
  input:
  output:
        "output_{i}.txt"
  shell:
        "python3 ../app.py  > {output}"

