# Snakefile that does the following:
# runs python3 ./app.py 10 times

rule all:
    input:
        expand("output_{i}.txt", i=range(10))

rule run_app:
    output:
        "output_{i}.txt"
    shell:
        "python ../app.py > output_{wildcards.i}.txt"
        


